import { addDays, subDays } from 'date-fns'
import {
  Property,
  Task,
  Financials,
  Message,
  Tenant,
  Owner,
  Partner,
} from '@/lib/types'

export const owners: Owner[] = [
  {
    id: 'owner1',
    name: 'John Doe',
    email: 'john.doe@example.com',
    phone: '+1 (555) 0101',
    status: 'active',
  },
  {
    id: 'owner2',
    name: 'Jane Smith',
    email: 'jane.smith@example.com',
    phone: '+1 (555) 0102',
    status: 'active',
  },
  {
    id: 'owner3',
    name: 'Robert Johnson',
    email: 'robert.j@example.com',
    phone: '+1 (555) 0103',
    status: 'active',
  },
  {
    id: 'owner4',
    name: 'Emily Davis',
    email: 'emily.d@example.com',
    phone: '+1 (555) 0104',
    status: 'inactive',
  },
]

export const properties: Property[] = [
  {
    id: 'prop1',
    name: 'Villa Sunshine',
    address: '123 Palm Street, Orlando, FL',
    type: 'House',
    community: 'Sunny Isles HOA',
    status: 'occupied',
    image: 'https://img.usecurling.com/p/400/300?q=modern%20villa',
    bedrooms: 4,
    bathrooms: 3,
    guests: 8,
    accessCode: '4921',
    wifi: 'Sunshine_Guest / sun123',
    ownerId: 'owner1',
    agentId: 'partner3',
  },
  {
    id: 'prop2',
    name: 'Downtown Condo',
    address: '450 Brickell Ave, Miami, FL',
    type: 'Condo',
    community: 'Brickell Heights',
    status: 'vacant',
    image: 'https://img.usecurling.com/p/400/300?q=luxury%20apartment',
    bedrooms: 2,
    bathrooms: 2,
    guests: 4,
    accessCode: '8812',
    wifi: 'BH_Guest / brickell',
    ownerId: 'owner2',
    agentId: 'partner3',
  },
  {
    id: 'prop3',
    name: 'Lakeside Retreat',
    address: '789 Lake View Dr, Kissimmee, FL',
    type: 'House',
    community: 'Lakefront HOA',
    status: 'maintenance',
    image: 'https://img.usecurling.com/p/400/300?q=lake%20house',
    bedrooms: 5,
    bathrooms: 4,
    guests: 12,
    accessCode: 'Locker: 1234',
    wifi: 'LakeView / fish123',
    ownerId: 'owner3',
  },
  {
    id: 'prop4',
    name: 'Cozy Cabin',
    address: '321 Pine Rd, Asheville, NC',
    type: 'House',
    community: 'Mountain Views',
    status: 'occupied',
    image: 'https://img.usecurling.com/p/400/300?q=cabin%20woods',
    bedrooms: 3,
    bathrooms: 2,
    guests: 6,
    accessCode: 'Key under mat',
    wifi: 'CabinWifi / bear',
    ownerId: 'owner4',
  },
]

export const tenants: Tenant[] = [
  {
    id: 'tenant1',
    name: 'Michael Scott',
    email: 'michael@dunder.com',
    phone: '+1 (555) 1111',
    propertyId: 'prop1',
    rentValue: 2500,
    status: 'active',
  },
  {
    id: 'tenant2',
    name: 'Jim Halpert',
    email: 'jim@dunder.com',
    phone: '+1 (555) 2222',
    propertyId: 'prop4',
    rentValue: 1800,
    status: 'active',
  },
]

export const partners: Partner[] = [
  {
    id: 'partner1',
    name: 'Maria Silva',
    type: 'cleaning',
    companyName: 'Sparkle Cleaners',
    email: 'maria@sparkle.com',
    phone: '+1 (555) 9991',
    status: 'active',
    rating: 4.8,
  },
  {
    id: 'partner2',
    name: 'Carlos Tech',
    type: 'maintenance',
    companyName: 'FixIt All',
    email: 'carlos@fixit.com',
    phone: '+1 (555) 9992',
    status: 'active',
    rating: 4.5,
  },
  {
    id: 'partner3',
    name: 'Sarah Connor',
    type: 'agent',
    companyName: 'Realty Group',
    email: 'sarah@realty.com',
    phone: '+1 (555) 9993',
    status: 'active',
    rating: 5.0,
  },
]

export const tasks: Task[] = [
  {
    id: 'task1',
    title: 'Limpeza Pós-Checkout',
    propertyId: 'prop1',
    propertyName: 'Villa Sunshine',
    propertyAddress: '123 Palm Street, Orlando, FL',
    propertyCommunity: 'Sunny Isles HOA',
    status: 'completed',
    type: 'cleaning',
    assignee: 'Maria Silva',
    assigneeId: 'partner1',
    date: subDays(new Date(), 1).toISOString(),
    priority: 'high',
    images: ['https://img.usecurling.com/p/300/200?q=clean%20bedroom'],
    evidence: [
      {
        id: 'ev1',
        url: 'https://img.usecurling.com/p/300/200?q=front%20door',
        type: 'arrival',
        timestamp: subDays(new Date(), 1).toISOString(),
        location: {
          lat: 28.5383,
          lng: -81.3792,
          address: '123 Palm Street, Orlando, FL',
        },
      },
      {
        id: 'ev2',
        url: 'https://img.usecurling.com/p/300/200?q=clean%20living%20room',
        type: 'completion',
        timestamp: subDays(new Date(), 1).toISOString(),
        location: {
          lat: 28.5383,
          lng: -81.3792,
          address: '123 Palm Street, Orlando, FL',
        },
      },
    ],
  },
  {
    id: 'task2',
    title: 'Reparo no Ar Condicionado',
    propertyId: 'prop3',
    propertyName: 'Lakeside Retreat',
    propertyAddress: '789 Lake View Dr, Kissimmee, FL',
    propertyCommunity: 'Lakefront HOA',
    status: 'in_progress',
    type: 'maintenance',
    assignee: 'Carlos Tech',
    assigneeId: 'partner2',
    date: new Date().toISOString(),
    priority: 'critical',
    images: ['https://img.usecurling.com/p/300/200?q=broken%20ac'],
    evidence: [
      {
        id: 'ev3',
        url: 'https://img.usecurling.com/p/300/200?q=ac%20unit',
        type: 'arrival',
        timestamp: new Date().toISOString(),
        location: {
          lat: 28.2919,
          lng: -81.4076,
          address: '789 Lake View Dr, Kissimmee, FL',
        },
      },
    ],
  },
  {
    id: 'task3',
    title: 'Inspeção de Rotina',
    propertyId: 'prop2',
    propertyName: 'Downtown Condo',
    propertyAddress: '450 Brickell Ave, Miami, FL',
    propertyCommunity: 'Brickell Heights',
    status: 'pending',
    type: 'inspection',
    assignee: 'Sarah Connor',
    assigneeId: 'partner3',
    date: addDays(new Date(), 2).toISOString(),
    priority: 'medium',
  },
  {
    id: 'task4',
    title: 'Limpeza de Piscina',
    propertyId: 'prop1',
    propertyName: 'Villa Sunshine',
    propertyAddress: '123 Palm Street, Orlando, FL',
    propertyCommunity: 'Sunny Isles HOA',
    status: 'pending',
    type: 'maintenance',
    assignee: 'Pool Services Inc',
    date: addDays(new Date(), 1).toISOString(),
    priority: 'medium',
    images: [],
  },
]

export const financials: Financials = {
  revenue: [
    { month: 'Jan', value: 12500 },
    { month: 'Fev', value: 15000 },
    { month: 'Mar', value: 18000 },
    { month: 'Abr', value: 14000 },
    { month: 'Mai', value: 21000 },
    { month: 'Jun', value: 24000 },
  ],
  expenses: [
    { category: 'Manutenção', value: 4500, fill: 'var(--color-maintenance)' },
    { category: 'Limpeza', value: 3200, fill: 'var(--color-cleaning)' },
    { category: 'Impostos', value: 2100, fill: 'var(--color-taxes)' },
    { category: 'Utilities', value: 1800, fill: 'var(--color-utilities)' },
  ],
  invoices: [
    {
      id: 'INV-001',
      description: 'Reparo Elétrico - Villa Sunshine',
      amount: 450.0,
      status: 'pending',
      date: '2024-05-10',
    },
    {
      id: 'INV-002',
      description: 'Taxa Mensal de Gestão',
      amount: 1200.0,
      status: 'approved',
      date: '2024-05-01',
    },
    {
      id: 'INV-003',
      description: 'Limpeza Pesada - Lakeside',
      amount: 350.0,
      status: 'paid',
      date: '2024-04-28',
    },
    {
      id: 'INV-004',
      description: 'Troca de Fechadura',
      amount: 180.0,
      status: 'pending',
      date: '2024-05-12',
    },
  ],
}

export const messages: Message[] = [
  {
    id: 'partner1',
    contact: 'Maria Silva (Cleaner)',
    type: 'partner',
    lastMessage: 'Terminei a limpeza na Villa Sunshine. Seguem as fotos.',
    time: '10:30',
    unread: 2,
    avatar: 'https://img.usecurling.com/ppl/thumbnail?gender=female&seed=1',
  },
  {
    id: 'owner1',
    contact: 'John Doe (Owner)',
    type: 'owner',
    lastMessage: 'Você pode verificar a correspondência?',
    time: 'Ontem',
    unread: 0,
    avatar: 'https://img.usecurling.com/ppl/thumbnail?gender=male&seed=2',
  },
  {
    id: 'partner2',
    contact: 'Carlos Tech (Maintenance)',
    type: 'partner',
    lastMessage: 'Preciso da aprovação para a peça do AC.',
    time: 'Ontem',
    unread: 1,
    avatar: 'https://img.usecurling.com/ppl/thumbnail?gender=male&seed=3',
  },
]
