import { addDays, subDays } from 'date-fns'
import {
  Property,
  Task,
  Financials,
  Message,
  Tenant,
  Owner,
  Partner,
  User,
} from '@/lib/types'

// System Users (Staff/Admins)
export const systemUsers: User[] = [
  {
    id: 'app_admin',
    name: 'Super Admin',
    email: 'admin@skip.com',
    role: 'app_owner',
    avatar: 'https://img.usecurling.com/ppl/thumbnail?gender=male&seed=99',
  },
  {
    id: 'plat_owner',
    name: 'Boss Manager',
    email: 'boss@manager.com',
    role: 'platform_owner',
    avatar: 'https://img.usecurling.com/ppl/thumbnail?gender=female&seed=98',
  },
  {
    id: 'plat_manager',
    name: 'Alice Manager',
    email: 'alice@manager.com',
    role: 'platform_manager',
    avatar: 'https://img.usecurling.com/ppl/thumbnail?gender=female&seed=97',
  },
  {
    id: 'plat_staff1',
    name: 'Bob Staff',
    email: 'bob@manager.com',
    role: 'platform_staff_long',
    avatar: 'https://img.usecurling.com/ppl/thumbnail?gender=male&seed=96',
  },
]

export const owners: Owner[] = [
  {
    id: 'owner1',
    name: 'John Doe',
    email: 'john.doe@example.com',
    phone: '+1 (555) 0101',
    status: 'active',
    role: 'property_owner',
    avatar: 'https://img.usecurling.com/ppl/thumbnail?gender=male&seed=2',
  },
  {
    id: 'owner2',
    name: 'Jane Smith',
    email: 'jane.smith@example.com',
    phone: '+1 (555) 0102',
    status: 'active',
    role: 'property_owner',
    avatar: 'https://img.usecurling.com/ppl/thumbnail?gender=female&seed=4',
  },
  {
    id: 'owner3',
    name: 'Robert Johnson',
    email: 'robert.j@example.com',
    phone: '+1 (555) 0103',
    status: 'active',
    role: 'property_owner',
    avatar: 'https://img.usecurling.com/ppl/thumbnail?gender=male&seed=5',
  },
  {
    id: 'owner4',
    name: 'Emily Davis',
    email: 'emily.d@example.com',
    phone: '+1 (555) 0104',
    status: 'inactive',
    role: 'property_owner',
    avatar: 'https://img.usecurling.com/ppl/thumbnail?gender=female&seed=6',
  },
]

export const properties: Property[] = [
  {
    id: 'prop1',
    name: 'Villa Sunshine',
    address: '123 Palm Street, Orlando, FL',
    type: 'House',
    community: 'Sunny Isles HOA',
    status: 'occupied',
    image: 'https://img.usecurling.com/p/400/300?q=modern%20villa',
    gallery: [
      'https://img.usecurling.com/p/400/300?q=modern%20villa',
      'https://img.usecurling.com/p/400/300?q=living%20room',
      'https://img.usecurling.com/p/400/300?q=kitchen%20modern',
      'https://img.usecurling.com/p/400/300?q=pool',
    ],
    bedrooms: 4,
    bathrooms: 3,
    guests: 8,
    wifiSsid: 'Sunshine_Guest',
    wifiPassword: 'sun123',
    accessCodeBuilding: '9988',
    accessCodeUnit: '4921',
    description: {
      pt: 'Uma bela villa com piscina aquecida e sala de jogos. Perfeita para famílias.',
      en: 'A beautiful villa with heated pool and game room. Perfect for families.',
      es: 'Una hermosa villa con piscina climatizada y sala de juegos. Perfecta para familias.',
    },
    hoaRules: {
      pt: 'Sem barulho após as 22h. Proibido estacionar na grama.',
      en: 'No noise after 10 PM. No parking on the grass.',
      es: 'Sin ruido después de las 22h. Prohibido estacionar en el césped.',
    },
    documents: [
      {
        id: 'd1',
        name: 'Contrato de Gestão.pdf',
        url: '#',
        date: '2024-01-15',
      },
      { id: 'd2', name: 'Planta Baixa.pdf', url: '#', date: '2023-12-10' },
    ],
    contractConfig: {
      expirationAlertDays: 30,
    },
    ownerId: 'owner1',
    agentId: 'partner3',
  },
  {
    id: 'prop2',
    name: 'Downtown Condo',
    address: '450 Brickell Ave, Miami, FL',
    type: 'Condo',
    community: 'Brickell Heights',
    status: 'vacant',
    image: 'https://img.usecurling.com/p/400/300?q=luxury%20apartment',
    gallery: ['https://img.usecurling.com/p/400/300?q=luxury%20apartment'],
    bedrooms: 2,
    bathrooms: 2,
    guests: 4,
    wifiSsid: 'BH_Guest',
    wifiPassword: 'brickell',
    accessCodeBuilding: '1234',
    accessCodeUnit: '8812',
    description: {
      pt: 'Condomínio de luxo no coração de Miami. Perto de tudo.',
      en: 'Luxury condo in the heart of Miami. Close to everything.',
      es: 'Condominio de lujo en el corazón de Miami. Cerca de todo.',
    },
    hoaRules: {
      pt: 'Apenas residentes na piscina.',
      en: 'Residents only at the pool.',
      es: 'Solo residentes en la piscina.',
    },
    ownerId: 'owner2',
    agentId: 'partner3',
  },
  {
    id: 'prop3',
    name: 'Lakeside Retreat',
    address: '789 Lake View Dr, Kissimmee, FL',
    type: 'House',
    community: 'Lakefront HOA',
    status: 'maintenance',
    image: 'https://img.usecurling.com/p/400/300?q=lake%20house',
    gallery: ['https://img.usecurling.com/p/400/300?q=lake%20house'],
    bedrooms: 5,
    bathrooms: 4,
    guests: 12,
    wifiSsid: 'LakeView',
    wifiPassword: 'fish123',
    accessCodeUnit: '5566',
    description: {
      pt: 'Retiro tranquilo à beira do lago.',
      en: 'Peaceful lakeside retreat.',
      es: 'Retiro tranquilo junto al lago.',
    },
    hoaRules: {
      pt: 'Não alimentar os jacarés.',
      en: 'Do not feed the alligators.',
      es: 'No alimentar a los caimanes.',
    },
    ownerId: 'owner3',
  },
  {
    id: 'prop4',
    name: 'Cozy Cabin',
    address: '321 Pine Rd, Asheville, NC',
    type: 'House',
    community: 'Mountain Views',
    status: 'occupied',
    image: 'https://img.usecurling.com/p/400/300?q=cabin%20woods',
    gallery: ['https://img.usecurling.com/p/400/300?q=cabin%20woods'],
    bedrooms: 3,
    bathrooms: 2,
    guests: 6,
    wifiSsid: 'CabinWifi',
    wifiPassword: 'bear',
    accessCodeUnit: 'KEY-BOX',
    description: {
      pt: 'Cabana aconchegante nas montanhas.',
      en: 'Cozy cabin in the mountains.',
      es: 'Cabaña acogedora en las montañas.',
    },
    hoaRules: {
      pt: 'Proibido fogueiras.',
      en: 'No open fires.',
      es: 'Prohibido fogatas.',
    },
    ownerId: 'owner4',
  },
]

export const tenants: Tenant[] = [
  {
    id: 'tenant1',
    name: 'Michael Scott',
    email: 'michael@dunder.com',
    phone: '+1 (555) 1111',
    propertyId: 'prop1',
    rentValue: 2500,
    leaseStart: '2024-01-01',
    leaseEnd: '2024-12-31',
    status: 'active',
    role: 'tenant',
    avatar: 'https://img.usecurling.com/ppl/thumbnail?gender=male&seed=10',
  },
  {
    id: 'tenant2',
    name: 'Jim Halpert',
    email: 'jim@dunder.com',
    phone: '+1 (555) 2222',
    propertyId: 'prop4',
    rentValue: 1800,
    leaseStart: '2024-03-01',
    leaseEnd: '2024-09-30',
    status: 'active',
    role: 'tenant',
    avatar: 'https://img.usecurling.com/ppl/thumbnail?gender=male&seed=11',
  },
]

export const partners: Partner[] = [
  {
    id: 'partner1',
    name: 'Maria Silva',
    type: 'cleaning',
    companyName: 'Sparkle Cleaners',
    email: 'maria@sparkle.com',
    phone: '+1 (555) 9991',
    status: 'active',
    rating: 4.8,
    role: 'partner',
    avatar: 'https://img.usecurling.com/ppl/thumbnail?gender=female&seed=1',
  },
  {
    id: 'partner2',
    name: 'Carlos Tech',
    type: 'maintenance',
    companyName: 'FixIt All',
    email: 'carlos@fixit.com',
    phone: '+1 (555) 9992',
    status: 'active',
    rating: 4.5,
    role: 'partner',
    avatar: 'https://img.usecurling.com/ppl/thumbnail?gender=male&seed=3',
  },
  {
    id: 'partner3',
    name: 'Sarah Connor',
    type: 'agent',
    companyName: 'Realty Group',
    email: 'sarah@realty.com',
    phone: '+1 (555) 9993',
    status: 'active',
    rating: 5.0,
    role: 'partner',
    avatar: 'https://img.usecurling.com/ppl/thumbnail?gender=female&seed=12',
  },
]

export const tasks: Task[] = [
  {
    id: 'task1',
    title: 'Limpeza Pós-Checkout',
    propertyId: 'prop1',
    propertyName: 'Villa Sunshine',
    propertyAddress: '123 Palm Street, Orlando, FL',
    propertyCommunity: 'Sunny Isles HOA',
    status: 'completed',
    type: 'cleaning',
    assignee: 'Maria Silva',
    assigneeId: 'partner1',
    date: subDays(new Date(), 1).toISOString(),
    priority: 'high',
    images: ['https://img.usecurling.com/p/300/200?q=clean%20bedroom'],
    evidence: [
      {
        id: 'ev1',
        url: 'https://img.usecurling.com/p/300/200?q=front%20door',
        type: 'arrival',
        timestamp: subDays(new Date(), 1).toISOString(),
        location: {
          lat: 28.5383,
          lng: -81.3792,
          address: '123 Palm Street, Orlando, FL',
        },
      },
      {
        id: 'ev2',
        url: 'https://img.usecurling.com/p/300/200?q=clean%20living%20room',
        type: 'completion',
        timestamp: subDays(new Date(), 1).toISOString(),
        location: {
          lat: 28.5383,
          lng: -81.3792,
          address: '123 Palm Street, Orlando, FL',
        },
      },
    ],
  },
  {
    id: 'task2',
    title: 'Reparo no Ar Condicionado',
    propertyId: 'prop3',
    propertyName: 'Lakeside Retreat',
    propertyAddress: '789 Lake View Dr, Kissimmee, FL',
    propertyCommunity: 'Lakefront HOA',
    status: 'in_progress',
    type: 'maintenance',
    assignee: 'Carlos Tech',
    assigneeId: 'partner2',
    date: new Date().toISOString(),
    priority: 'critical',
    images: ['https://img.usecurling.com/p/300/200?q=broken%20ac'],
    evidence: [
      {
        id: 'ev3',
        url: 'https://img.usecurling.com/p/300/200?q=ac%20unit',
        type: 'arrival',
        timestamp: new Date().toISOString(),
        location: {
          lat: 28.2919,
          lng: -81.4076,
          address: '789 Lake View Dr, Kissimmee, FL',
        },
      },
    ],
  },
  {
    id: 'task3',
    title: 'Inspeção de Rotina',
    propertyId: 'prop2',
    propertyName: 'Downtown Condo',
    propertyAddress: '450 Brickell Ave, Miami, FL',
    propertyCommunity: 'Brickell Heights',
    status: 'pending',
    type: 'inspection',
    assignee: 'Sarah Connor',
    assigneeId: 'partner3',
    date: addDays(new Date(), 2).toISOString(),
    priority: 'medium',
  },
  {
    id: 'task4',
    title: 'Limpeza de Piscina',
    propertyId: 'prop1',
    propertyName: 'Villa Sunshine',
    propertyAddress: '123 Palm Street, Orlando, FL',
    propertyCommunity: 'Sunny Isles HOA',
    status: 'pending',
    type: 'maintenance',
    assignee: 'Pool Services Inc',
    date: addDays(new Date(), 1).toISOString(),
    priority: 'medium',
    images: [],
  },
]

export const financials: Financials = {
  revenue: [
    { month: 'Jan', value: 12500 },
    { month: 'Fev', value: 15000 },
    { month: 'Mar', value: 18000 },
    { month: 'Abr', value: 14000 },
    { month: 'Mai', value: 21000 },
    { month: 'Jun', value: 24000 },
  ],
  expenses: [
    { category: 'Manutenção', value: 4500, fill: 'var(--color-maintenance)' },
    { category: 'Limpeza', value: 3200, fill: 'var(--color-cleaning)' },
    { category: 'Impostos', value: 2100, fill: 'var(--color-taxes)' },
    { category: 'Utilities', value: 1800, fill: 'var(--color-utilities)' },
  ],
  invoices: [
    {
      id: 'INV-001',
      description: 'Reparo Elétrico - Villa Sunshine',
      amount: 450.0,
      status: 'pending',
      date: '2024-05-10',
    },
    {
      id: 'INV-002',
      description: 'Taxa Mensal de Gestão',
      amount: 1200.0,
      status: 'approved',
      date: '2024-05-01',
    },
    {
      id: 'INV-003',
      description: 'Limpeza Pesada - Lakeside',
      amount: 350.0,
      status: 'paid',
      date: '2024-04-28',
    },
    {
      id: 'INV-004',
      description: 'Troca de Fechadura',
      amount: 180.0,
      status: 'pending',
      date: '2024-05-12',
    },
  ],
}

// Initial Messages for 'plat_manager' (Alice Manager)
export const messages: Message[] = [
  {
    id: 'conv1',
    contact: 'Maria Silva (Cleaner)',
    contactId: 'partner1',
    ownerId: 'plat_manager',
    type: 'partner',
    lastMessage: 'Terminei a limpeza na Villa Sunshine. Seguem as fotos.',
    time: '10:30',
    unread: 2,
    avatar: 'https://img.usecurling.com/ppl/thumbnail?gender=female&seed=1',
    history: [
      {
        id: 'm1',
        text: 'Bom dia, você vai na Villa Sunshine hoje?',
        sender: 'me',
        timestamp: '09:00',
      },
      {
        id: 'm2',
        text: 'Sim, estou a caminho.',
        sender: 'other',
        timestamp: '09:15',
      },
      {
        id: 'm3',
        text: 'Terminei a limpeza na Villa Sunshine. Seguem as fotos.',
        sender: 'other',
        timestamp: '10:30',
      },
    ],
  },
  {
    id: 'conv2',
    contact: 'John Doe (Owner)',
    contactId: 'owner1',
    ownerId: 'plat_manager',
    type: 'property_owner',
    lastMessage: 'Você pode verificar a correspondência?',
    time: 'Ontem',
    unread: 0,
    avatar: 'https://img.usecurling.com/ppl/thumbnail?gender=male&seed=2',
    history: [
      {
        id: 'm1',
        text: 'Você pode verificar a correspondência?',
        sender: 'other',
        timestamp: '16:00',
      },
    ],
  },
]

export const owner1Messages: Message[] = [
  {
    id: 'conv_owner1_1',
    contact: 'Alice Manager',
    contactId: 'plat_manager',
    ownerId: 'owner1',
    type: 'platform_manager',
    lastMessage: 'Verificamos e colocamos na sua mesa.',
    time: 'Ontem',
    unread: 1,
    avatar: 'https://img.usecurling.com/ppl/thumbnail?gender=female&seed=97',
    history: [
      {
        id: 'm1',
        text: 'Você pode verificar a correspondência?',
        sender: 'me',
        timestamp: '16:00',
      },
      {
        id: 'm2',
        text: 'Verificamos e colocamos na sua mesa.',
        sender: 'other',
        timestamp: '16:15',
      },
    ],
  },
]

export const partner1Messages: Message[] = [
  {
    id: 'conv_part1_1',
    contact: 'Alice Manager',
    contactId: 'plat_manager',
    ownerId: 'partner1',
    type: 'platform_manager',
    lastMessage: 'Ok, obrigada!',
    time: '10:35',
    unread: 0,
    avatar: 'https://img.usecurling.com/ppl/thumbnail?gender=female&seed=97',
    history: [
      {
        id: 'm1',
        text: 'Terminei a limpeza na Villa Sunshine.',
        sender: 'me',
        timestamp: '10:30',
      },
      {
        id: 'm2',
        text: 'Ok, obrigada!',
        sender: 'other',
        timestamp: '10:35',
      },
    ],
  },
]
