import { useState, useMemo } from 'react'
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription,
  DialogFooter,
} from '@/components/ui/dialog'
import { Button } from '@/components/ui/button'
import { Checkbox } from '@/components/ui/checkbox'
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from '@/components/ui/table'
import { useToast } from '@/hooks/use-toast'
import useTaskStore from '@/stores/useTaskStore'
import useAuthStore from '@/stores/useAuthStore'
import useFinancialStore from '@/stores/useFinancialStore'
import { format } from 'date-fns'
import { Invoice } from '@/lib/types'
import { ScrollArea } from '@/components/ui/scroll-area'

interface TaskInvoiceDialogProps {
  open: boolean
  onOpenChange: (open: boolean) => void
}

export function TaskInvoiceDialog({
  open,
  onOpenChange,
}: TaskInvoiceDialogProps) {
  const { tasks } = useTaskStore()
  const { currentUser } = useAuthStore()
  const { addInvoice } = useFinancialStore()
  const { toast } = useToast()

  const [selectedTasks, setSelectedTasks] = useState<string[]>([])

  // Determine user role and corresponding logic
  const isTeamMember = currentUser.role === 'partner_employee'
  const isPartner = currentUser.role === 'partner'
  const isAdminOrPM = ['platform_owner', 'software_tenant'].includes(
    currentUser.role,
  )

  // Filter tasks available for invoicing
  const invoiceableTasks = useMemo(() => {
    return tasks.filter((task) => {
      // Must be completed
      if (task.status !== 'completed') return false

      if (isTeamMember) {
        // Team member sees tasks assigned to them with a payout value
        return (
          task.partnerEmployeeId === currentUser.id &&
          task.teamMemberPayout &&
          task.teamMemberPayout > 0
        )
      }

      if (isPartner) {
        // Partner sees tasks assigned to them (company) with a price
        return (
          task.assigneeId === currentUser.id && task.price && task.price > 0
        )
      }

      if (isAdminOrPM) {
        // PM sees all completed tasks with price, can invoice on behalf of anyone
        return task.price && task.price > 0
      }

      return false
    })
  }, [tasks, currentUser, isTeamMember, isPartner, isAdminOrPM])

  // Calculate total
  const totalAmount = useMemo(() => {
    return selectedTasks.reduce((acc, taskId) => {
      const task = tasks.find((t) => t.id === taskId)
      if (!task) return acc

      if (isTeamMember) return acc + (task.teamMemberPayout || 0)
      return acc + (task.price || 0)
    }, 0)
  }, [selectedTasks, tasks, isTeamMember])

  const handleSelectAll = (checked: boolean) => {
    if (checked) {
      setSelectedTasks(invoiceableTasks.map((t) => t.id))
    } else {
      setSelectedTasks([])
    }
  }

  const handleSelectTask = (taskId: string, checked: boolean) => {
    if (checked) {
      setSelectedTasks((prev) => [...prev, taskId])
    } else {
      setSelectedTasks((prev) => prev.filter((id) => id !== taskId))
    }
  }

  const handleGenerateInvoice = () => {
    if (selectedTasks.length === 0) return

    let invoiceType: Invoice['type'] = 'generic'
    if (isTeamMember) invoiceType = 'team_to_partner'
    else if (isPartner) invoiceType = 'partner_to_pm'
    else if (isAdminOrPM) invoiceType = 'admin_to_pm'

    const invoice: Invoice = {
      id: `inv-${Date.now()}`,
      description: `Invoice generated by ${currentUser.name} for ${selectedTasks.length} tasks`,
      amount: totalAmount,
      status: 'pending',
      date: new Date().toISOString(),
      fromId: currentUser.id,
      type: invoiceType,
    }

    addInvoice(invoice)

    toast({
      title: 'Invoice Generated',
      description: `Invoice for $${totalAmount.toFixed(2)} created successfully.`,
    })

    onOpenChange(false)
    setSelectedTasks([])
  }

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="max-w-3xl max-h-[90vh] flex flex-col">
        <DialogHeader>
          <DialogTitle>Generate Invoice</DialogTitle>
          <DialogDescription>
            Select completed tasks to include in this invoice.
          </DialogDescription>
        </DialogHeader>

        <div className="flex-1 overflow-hidden flex flex-col gap-4">
          <div className="flex justify-between items-center p-2 bg-muted/30 rounded-md">
            <div className="flex items-center gap-2">
              <Checkbox
                checked={
                  selectedTasks.length === invoiceableTasks.length &&
                  invoiceableTasks.length > 0
                }
                onCheckedChange={(c) => handleSelectAll(c as boolean)}
              />
              <span className="text-sm font-medium">Select All</span>
            </div>
            <div className="text-sm">
              Selected:{' '}
              <span className="font-bold">{selectedTasks.length}</span>
            </div>
          </div>

          <ScrollArea className="flex-1 border rounded-md h-[300px]">
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead className="w-[50px]"></TableHead>
                  <TableHead>Date</TableHead>
                  <TableHead>Task</TableHead>
                  <TableHead>Property</TableHead>
                  <TableHead className="text-right">Value</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {invoiceableTasks.length === 0 ? (
                  <TableRow>
                    <TableCell colSpan={5} className="text-center py-8">
                      No invoiceable tasks found.
                    </TableCell>
                  </TableRow>
                ) : (
                  invoiceableTasks.map((task) => (
                    <TableRow key={task.id}>
                      <TableCell>
                        <Checkbox
                          checked={selectedTasks.includes(task.id)}
                          onCheckedChange={(c) =>
                            handleSelectTask(task.id, c as boolean)
                          }
                        />
                      </TableCell>
                      <TableCell>
                        {format(new Date(task.date), 'dd/MM/yyyy')}
                      </TableCell>
                      <TableCell className="font-medium">
                        {task.title}
                      </TableCell>
                      <TableCell>{task.propertyName}</TableCell>
                      <TableCell className="text-right font-semibold">
                        $
                        {isTeamMember
                          ? task.teamMemberPayout?.toFixed(2)
                          : task.price?.toFixed(2)}
                      </TableCell>
                    </TableRow>
                  ))
                )}
              </TableBody>
            </Table>
          </ScrollArea>
        </div>

        <DialogFooter className="flex justify-between items-center w-full">
          <div className="text-lg font-bold">
            Total: ${totalAmount.toFixed(2)}
          </div>
          <div className="flex gap-2">
            <Button variant="outline" onClick={() => onOpenChange(false)}>
              Cancel
            </Button>
            <Button
              onClick={handleGenerateInvoice}
              disabled={selectedTasks.length === 0}
              className="bg-trust-blue"
            >
              Generate Invoice
            </Button>
          </div>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  )
}
