import { useContext } from 'react'
import { AppContext } from '@/stores/AppContext'
import { Button } from '@/components/ui/button'
import {
  Card,
  CardContent,
  CardHeader,
  CardTitle,
  CardDescription,
} from '@/components/ui/card'
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from '@/components/ui/table'
import { Badge } from '@/components/ui/badge'
import { Moon, RefreshCw, FileCheck } from 'lucide-react'
import { formatCurrency, formatDate } from '@/lib/utils'
import useLanguageStore from '@/stores/useLanguageStore'

export default function NightAudit() {
  const context = useContext(AppContext)
  const { nightAudits, runNightAudit } = context!
  const { language } = useLanguageStore()

  return (
    <div className="flex flex-col gap-6">
      <div className="flex justify-between items-center">
        <div>
          <h1 className="text-3xl font-bold tracking-tight text-navy flex items-center gap-2">
            <Moon className="h-8 w-8 text-indigo-600" /> Night Audit
          </h1>
          <p className="text-muted-foreground">
            Daily financial reconciliation and reporting.
          </p>
        </div>
        <Button
          onClick={runNightAudit}
          className="bg-indigo-600 hover:bg-indigo-700 gap-2"
        >
          <RefreshCw className="h-4 w-4" /> Run Night Audit
        </Button>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
        <Card>
          <CardHeader className="pb-2">
            <CardTitle className="text-sm font-medium">
              Last Audit Revenue
            </CardTitle>
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold text-green-600">
              {nightAudits.length > 0
                ? formatCurrency(nightAudits[0].totalRevenue, language)
                : '-'}
            </div>
            <p className="text-xs text-muted-foreground mt-1">
              Date:{' '}
              {nightAudits.length > 0
                ? formatDate(nightAudits[0].date, language)
                : 'N/A'}
            </p>
          </CardContent>
        </Card>
        <Card>
          <CardHeader className="pb-2">
            <CardTitle className="text-sm font-medium">
              Occupancy Count
            </CardTitle>
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold text-blue-600">
              {nightAudits.length > 0 ? nightAudits[0].totalOccupancy : '-'}
            </div>
          </CardContent>
        </Card>
        <Card>
          <CardHeader className="pb-2">
            <CardTitle className="text-sm font-medium">Status</CardTitle>
          </CardHeader>
          <CardContent>
            <Badge
              variant="outline"
              className="bg-green-50 text-green-700 border-green-200"
            >
              {nightAudits.length > 0 ? 'Verified' : 'Pending'}
            </Badge>
          </CardContent>
        </Card>
      </div>

      <Card>
        <CardHeader>
          <CardTitle>Audit History</CardTitle>
          <CardDescription>Log of past night audits.</CardDescription>
        </CardHeader>
        <CardContent>
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead>Date</TableHead>
                <TableHead>Generated By</TableHead>
                <TableHead>Revenue</TableHead>
                <TableHead>Room Charges</TableHead>
                <TableHead>Service Fees</TableHead>
                <TableHead>Status</TableHead>
                <TableHead className="text-right">Actions</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {nightAudits.length === 0 ? (
                <TableRow>
                  <TableCell
                    colSpan={7}
                    className="text-center py-8 text-muted-foreground"
                  >
                    No audits generated yet.
                  </TableCell>
                </TableRow>
              ) : (
                nightAudits.map((audit) => (
                  <TableRow key={audit.id}>
                    <TableCell className="font-medium">
                      {formatDate(audit.date, language)}
                    </TableCell>
                    <TableCell>{audit.generatedBy}</TableCell>
                    <TableCell className="text-green-700 font-bold">
                      {formatCurrency(audit.totalRevenue, language)}
                    </TableCell>
                    <TableCell>
                      {formatCurrency(audit.roomCharges, language)}
                    </TableCell>
                    <TableCell>
                      {formatCurrency(audit.serviceFees, language)}
                    </TableCell>
                    <TableCell>
                      <Badge variant="outline" className="capitalize">
                        {audit.status}
                      </Badge>
                    </TableCell>
                    <TableCell className="text-right">
                      <Button variant="ghost" size="sm">
                        <FileCheck className="h-4 w-4" />
                      </Button>
                    </TableCell>
                  </TableRow>
                ))
              )}
            </TableBody>
          </Table>
        </CardContent>
      </Card>
    </div>
  )
}
