import { useMemo, useState } from 'react'
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from '@/components/ui/card'
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select'
import {
  ChartContainer,
  ChartTooltip,
  ChartTooltipContent,
  ChartLegend,
  ChartLegendContent,
} from '@/components/ui/chart'
import {
  Bar,
  BarChart,
  XAxis,
  YAxis,
  CartesianGrid,
  ResponsiveContainer,
} from 'recharts'
import usePartnerStore from '@/stores/usePartnerStore'
import { subDays, isAfter, subMonths } from 'date-fns'

export function ServiceAnalytics() {
  const { tasks, serviceCategories } = usePartnerStore()
  const [timeRange, setTimeRange] = useState('90days')

  const filteredData = useMemo(() => {
    const now = new Date()
    let startDate = subDays(now, 90)

    if (timeRange === '30days') startDate = subDays(now, 30)
    if (timeRange === 'year') startDate = subMonths(now, 12)

    // Filter tasks within date range and calculate revenue
    const relevantTasks = tasks.filter(
      (t) =>
        t.status === 'completed' &&
        t.date &&
        isAfter(new Date(t.date), startDate),
    )

    // Aggregate by category
    // Since Tasks don't have categoryId directly, we try to match type to category name
    // or fallback to 'Uncategorized'
    const categoryRevenue: Record<string, number> = {}

    relevantTasks.forEach((task) => {
      // Logic:
      // 1. Try to find category matching task.type (normalized)
      // 2. Fallback to 'Uncategorized'
      let catName = 'Other'

      const matchedCat = serviceCategories.find(
        (c) => c.name.toLowerCase() === task.type.toLowerCase(),
      )
      if (matchedCat) {
        catName = matchedCat.name
      } else {
        // Try finding by inventory/title keywords? Keep it simple for now
        if (task.type === 'cleaning') catName = 'Cleaning'
        else if (task.type === 'maintenance') catName = 'Maintenance'
        else if (task.type === 'inspection') catName = 'Inspection'
      }

      const revenue = task.billableAmount || 0
      // If we want Profit: revenue - (task.laborCost || 0) - (task.materialCost || 0)
      // User story says "Revenue generated".

      categoryRevenue[catName] = (categoryRevenue[catName] || 0) + revenue
    })

    return Object.entries(categoryRevenue).map(([name, value]) => ({
      name,
      revenue: value,
      fill: serviceCategories.find((c) => c.name === name)?.color || '#94a3b8',
    }))
  }, [tasks, timeRange, serviceCategories])

  const chartConfig = useMemo(() => {
    const config: Record<string, { label: string; color: string }> = {
      revenue: {
        label: 'Revenue',
        color: 'hsl(var(--primary))',
      },
    }
    filteredData.forEach((item) => {
      config[item.name] = {
        label: item.name,
        color: item.fill,
      }
    })
    return config
  }, [filteredData])

  return (
    <div className="grid gap-6">
      <Card>
        <CardHeader>
          <div className="flex items-center justify-between">
            <div>
              <CardTitle>Service Revenue Report</CardTitle>
              <CardDescription>
                Total revenue generated by completed service tasks.
              </CardDescription>
            </div>
            <div className="w-[180px]">
              <Select value={timeRange} onValueChange={setTimeRange}>
                <SelectTrigger>
                  <SelectValue placeholder="Select range" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="30days">Last 30 Days</SelectItem>
                  <SelectItem value="90days">Last 3 Months</SelectItem>
                  <SelectItem value="year">Last Year</SelectItem>
                </SelectContent>
              </Select>
            </div>
          </div>
        </CardHeader>
        <CardContent>
          <div className="h-[400px] w-full">
            {filteredData.length > 0 ? (
              <ChartContainer config={chartConfig} className="h-full w-full">
                <BarChart data={filteredData}>
                  <CartesianGrid vertical={false} strokeDasharray="3 3" />
                  <XAxis
                    dataKey="name"
                    tickLine={false}
                    tickMargin={10}
                    axisLine={false}
                  />
                  <YAxis
                    tickFormatter={(value) => `$${value}`}
                    axisLine={false}
                    tickLine={false}
                  />
                  <ChartTooltip content={<ChartTooltipContent />} />
                  <ChartLegend content={<ChartLegendContent />} />
                  <Bar dataKey="revenue" radius={[4, 4, 0, 0]} />
                </BarChart>
              </ChartContainer>
            ) : (
              <div className="h-full flex items-center justify-center text-muted-foreground">
                No revenue data available for this period.
              </div>
            )}
          </div>
        </CardContent>
      </Card>
    </div>
  )
}
